### ISSUE TITLE
UnicodeEncodeError on removeWhitespaceLines() method

### ISSUE THREAD

**Issue by nelsonni** [smckee6192/CS569FinalProject#1]
Encountered when mining merges and conflicts in the `FreeCodeCamp` repo:

``` term
('Unexpected error:', <type 'exceptions.UnicodeEncodeError'>)
Traceback (most recent call last):
  File "local_crawler.py", line 225, in <module>
    main()
  File "local_crawler.py", line 69, in main
    classification = classifier.classifyResolutionPattern(file[0]['lines'], file[1]['lines'], getDiff(commit))
  File "/Users/nelsonni/Project/CS569FinalProject/pattern_classifier.py", line 6, in classifyResolutionPattern
    mergeVersion = removeWhitespaceLines(mergeVersion)
  File "/Users/nelsonni/Project/CS569FinalProject/pattern_classifier.py", line 176, in removeWhitespaceLines
    line = str(line)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb7' in position 0: ordinal not in range(128)
```

**Comment by mckeesh** [comment]
Seems to be fixed by switching to utf-8 instead of ascii.
